### ISSUE TITLE
Question about the `pfps` storage

### ISSUE THREAD

**Issue by NiobiumZeit** [ForeverPFP/contract#1]
` mapping(address => IPFPBinding.PFP) private pfps;`

Seems this can only store the latest delegation for the address, so if someone wanna bind different PFP to the same address, it will be conflicted.

**Comment by PirateCode-eth** [comment]
it is designed to 1:1 mapping, which will be overrided:
https://github.com/ForeverPFP/ForeverPFP/pull/2

**Comment by NiobiumZeit** [comment]
Why design it as 1:1 mapping, which scene need override the mapping?

**Comment by PirateCode-eth** [comment]
You can check the Readme.md, it’s more like a ENS reverse record which
means 1:1 mapping.

**Comment by NiobiumZeit** [comment]
But it will be confused, for example, maybe most time u wanna to show ur avatar as BAYC#1, but u buy more BAYC and bind them, ur avatar will always become the latest one, maybe it is better to let user choose which one he wanna set for reverse record.

**Comment by PirateCode-eth** [comment]
He can choose, but buying one doesn’t mean to bind one, that’s what forever
means, it works the same way as ENS reverse record.

**Comment by NiobiumZeit** [comment]
ENS reverse record need explicit set, if u do the replace automatically, it will be so strange, maybe only the first time should the reverse recrod be set automatically? or add another parameter to check if user wanna replace it?

**Comment by PirateCode-eth** [comment]
If you set ens record reverse to another ens, it will be replaced
automatically.

**Comment by PirateCode-eth** [comment]
> ENS reverse record need explicit set, if u do the replace automatically, it will be so strange, maybe only the first time should the reverse recrod be set automatically? or add another parameter to check if user wanna replace it?

This bind and unbind need to be call explicit as well like ENS reverse record.

**Comment by NiobiumZeit** [comment]
So u mean that this is not a tool that like delegate.cash to let user use other protocols without original NFT, just to do something like ENS do?

**Comment by PirateCode-eth** [comment]
It’s more like an ENS reverse record for PFP with delegation support for
hotwallet.

**Comment by PirateCode-eth** [comment]
@NiobiumZeit is there any more question here? :)
