### ISSUE TITLE
How to bind correctly 

### ISSUE THREAD

**Issue by 0xtiby** [ForeverPFP/contract#11]
While working on frontend I bind mutiple times different PFPs. 
I was expecting that when I bind a new pfp the old binding get removed. 
Instead I have three PFPs binded and I get execution reverted: duplicated binding on all.

Does the workflow is that to bind a new PFP  I need to manually remove old one before ? 

[https://goerli.etherscan.io/address/0x18fb660e593efba8bc7d8a2f8f83ae1cb8fa4026#internaltx](https://goerli.etherscan.io/address/0x18fb660e593efba8bc7d8a2f8f83ae1cb8fa4026#internaltx
)

@PirateCode-eth

**Comment by PirateCode-eth** [comment]
Let me check, it maybe a bug, will update it soon. when bind a new PFP, it supposed to be override the old binding.

**Comment by PirateCode-eth** [comment]
goerli etherscan is broken I can't open your link, I checked the code, looks like you bind same PFP for same address?
https://github.com/ForeverPFP/contract/blob/main/src/ForeverPFP.sol#L38
there is a testcase here for duplication binding:
https://github.com/ForeverPFP/contract/blob/main/test/ForeverPFP.t.sol#L82

**Comment by 0xtiby** [comment]
What I do is I take one of my NFT I bind it to my wallet. Next I select an other one and binded it to the same wallet. If I came back to previous and try to bind it again it says duplicate binding. 
![image](https://user-images.githubusercontent.com/101003754/230582255-b1279588-0f38-4335-a4ca-ef3acecbaa4d.png)
![image](https://user-images.githubusercontent.com/101003754/230582304-c8325cb0-61e0-4edd-bf03-92d1e539f3fe.png)
![image](https://user-images.githubusercontent.com/101003754/230582343-69fc32ea-e67e-43c4-8e2b-e7d3a66b497e.png)

**Comment by PirateCode-eth** [comment]
Will check about it, looks like it’s a bug.

**Comment by PirateCode-eth** [comment]
it's fixed in https://github.com/ForeverPFP/contract/pull/12, will deploy a new testnet contract soon. :) you can review it if you like.
