### ISSUE TITLE
Unbind delegate not possible ? 

### ISSUE THREAD

**Issue by 0xtiby** [ForeverPFP/contract#19]
When looking at the contract it's look like we can't unbind a delegate ? I'm wrong ?

**Comment by PirateCode-eth** [comment]
unbind by owner or bind/delegate to a new address is the way to unbind a delegate.

**Comment by PirateCode-eth** [comment]
update the doc here: https://github.com/ForeverPFP/doc#how-can-i-unbind-the-delegate

**Comment by PirateCode-eth** [comment]
if no more question about this, should we close it? @0xtiby

**Comment by 0xtiby** [comment]
Yes sure.
